### ISSUE TITLE
change core branch `master` to `main`

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm-viz-demo#21]
Wait for machinshin's #20 to land

**Comment by machinshin** [comment]
@StoneCypher : #20 has landed

**Comment by StoneCypher** [comment]
orite, thanks

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/117339238-5e72cd80-ae54-11eb-897c-fc6f53dcb740.png)
