### ISSUE TITLE
GitHub Pages link is broken :(

### ISSUE THREAD

**Issue by Zearin** [StoneCypher/jssm-viz-demo#27]
Probably from changing the branch name.

https://stonecypher.github.io/jssm-viz-demo/graph_explorer.html

**Comment by StoneCypher** [comment]
Fuck.  Shenanigans.

It looks like the `index.html` is just missing from [the relevant directory](https://github.com/StoneCypher/jssm-viz-demo/tree/main/docs)

Fundamentally this is my fault for not setting up more test stuff on this repo

**Comment by StoneCypher** [comment]
uh no, index isn't the right file, the right file is right there.  sorry, tired

hm, maybe it is about the branch name

turning off then back on, as is the tradition of the programmer tribe

**Comment by StoneCypher** [comment]
yep, you were right, and that fixed it

fundamentally this is still my fault, just for lack of having an uptime thing instead

**Comment by StoneCypher** [comment]
thank you for catching this and notifying me
