### ISSUE TITLE
Live demo doesn't render persisted editor content on reload.

### ISSUE THREAD

**Issue by samsch** [StoneCypher/jssm-viz-demo#3]
If you make changes to the state machine code in the editor, then refresh the page, the changes in the editor persist, but the visualization resets to the initial state machine. If you then make any edit in the editor, the visualization updates to match.

**Comment by samsch** [comment]
This didn't fix the issue, but I see what the actual problem is now. In Chrome, when you refresh, the textarea contains the default content. Firefox instead appears to autofill the textarea with the content from before refreshing. This autofill doesn't trigger onkeyup, which is used to detect changes.

Two obvious possible fixes:
- Add `autocomplete="off"` to the textarea. This should give the same behavior as Chrome.
- Detect autofilled value, and update the visualization based on it.

**Comment by StoneCypher** [comment]
oh, i didn't test firefox

will refix

**Comment by StoneCypher** [comment]
Closed in favor of mono-tracker

https://github.com/StoneCypher/fsl/issues/86
